Feature/reservation status UI
ANTARES-KOR/yonsei-space-system pull request #42
Opened 2022-09-04 11:42 UTC by eunddodi

### What
* 대관 현황 조회 UI 구현
* 대관 현황 정보 관련 인터페이스 정의

### Why

### How
`Table` 컴포넌트 내에 `Column` 컴포넌트 (n+1)개 
👉 n: 오늘 기준 조회 가능한 토요일 수

`Column` 컴포넌트 각각이 날짜 하루를 의미

fullCalender처럼 시간 기준으로 `SingleReservationInfo`의 top, height를 계산(06:00 시작을 기준으로)
이때 10분 당 0.7rem, UI상 row 개당 2.1rem

### Reference

2022-09-04 15:45 UTC, ANTARES-KOR commented on frontend/src/atom.ts
> +const selectState = atom<string | null>({
한가지 아쉬운 점은, `SelectState` 하나만 보아서는 이게 무엇을 가리키는 상태인지 알기 어려운 것 같아요!
변수에서 이것이 가리키는 상태에 대한 정보를 더 주면 좀 더 읽기 좋은 코드가 될 것 같습니다

2022-09-04 15:51 UTC, ANTARES-KOR commented on frontend/src/components/Column.tsx
> +  );
Array 메서드를 잘 사용한 점이 좋네요!

한가지는 어차피 이 `timeSlots` 라는 값이 상수니깐 굳이 `useMemo`로 메모하지 않고 `<Column/>` 외부에 상수로서 정의하는 것은 어떨까요?

2022-09-04 15:53 UTC, ANTARES-KOR requested changes
굳굳!

내가 브랜치 업데이트해둬서 작업할 때 한번 리모트에서 이 브랜치에 대해서 `pull` 받고 작업하는게 좋을듯!

그리구 리뷰 받고 나서 PR 닫고 새로 열지말구, 이 브랜치에 변경사항 commit한다음에 re-request review 하는식으로 한번 해봅시다ㅎㅎ

2022-09-06 03:10 UTC, eunddodi commented on frontend/src/atom.ts
> +const selectState = atom<string | null>({
맞아요 이때 아직 현황조회 로직 짜기 전이라 애매해서 그냥 이렇게 만들었던 기억이

2022-09-06 03:11 UTC, eunddodi commented on frontend/src/components/Column.tsx
> +  );
오빠 코드에서 constants 모아 놓은 것처럼? 오케

2022-09-14 01:43 UTC, ANTARES-KOR approved these changes
LGTM :)

리뷰가 늦어서 제성합니다..ㅎㅎ

2022-09-14 12:43 UTC, eunddodi commented
> 

괜찮슴미당~~~ 감사합니당

2022-09-14 12:44 UTC, merged